### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by nlpCSir** [hua-qi/POYI#1]
你好，你的topicList好像有错误，请问您可以提供正确的吗？我想借鉴学习一下

**Comment by hua-qi** [comment]
能麻烦你把具体的错误信息告诉我吗，因为我在我本地跑是 ok 的，我不太清楚是哪里造成了错误。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hua-qi/POYI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 晚上9:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hua-qi/POYI] 大佬你好 (Issue #1)





 
你好，你的topicList好像有错误，请问您可以提供正确的吗？我想借鉴学习一下
